package org.wayland4j.scanner.codegen;

import org.wayland4j.scanner.model.Arg;
import org.wayland4j.scanner.model.ArgType;
import org.wayland4j.scanner.model.Description;
import org.wayland4j.scanner.model.EnumDef;
import org.wayland4j.scanner.model.EnumEntry;
import org.wayland4j.scanner.model.Event;
import org.wayland4j.scanner.model.Interface;
import org.wayland4j.scanner.model.Protocol;
import org.wayland4j.scanner.model.Request;
import org.wayland4j.scanner.naming.Names;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.OptionalInt;
import java.util.stream.Collectors;

/**
 * Renders a parsed {@link Protocol} into Java source code, one file per
 * interface. The emitter is intentionally JDK-only; templates are multi-line
 * text blocks composed with {@link String#formatted}.
 */
public final class JavaEmitter {

    private static final String GENERATED_HEADER = """
            // Generated by org.wayland4j.scanner — DO NOT EDIT.
            // Source protocol: %s
            """;

    /** Writes one .java file per interface under {@code outputRoot}. */
    public void emit(Protocol protocol, String packageName, Path outputRoot) throws IOException {
        CodegenContext ctx = new CodegenContext(protocol, packageName);
        Path packageDir = outputRoot.resolve(packageName.replace('.', '/'));
        Files.createDirectories(packageDir);
        for (Interface iface : protocol.interfaces()) {
            String fileName = Names.pascal(iface.name()) + ".java";
            String body = renderInterfaceFile(ctx, iface);
            Files.writeString(packageDir.resolve(fileName), body, StandardCharsets.UTF_8);
        }
    }

    /** Test seam: render a single interface's source to a string. */
    public String renderInterfaceFile(Protocol protocol, String packageName, Interface iface) {
        return renderInterfaceFile(new CodegenContext(protocol, packageName), iface);
    }

    // ---- top level --------------------------------------------------------

    private String renderInterfaceFile(CodegenContext ctx, Interface iface) {
        StringBuilder sb = new StringBuilder();
        sb.append(GENERATED_HEADER.formatted(ctx.protocol().name()));
        sb.append("package ").append(ctx.packageName()).append(";\n\n");

        sb.append(renderJavadoc(iface.description(), iface.version(), OptionalInt.empty()));
        sb.append("public interface ").append(Names.pascal(iface.name())).append(" {\n\n");
        sb.append(indent(1, "public static final String INTERFACE_NAME = \"" + iface.name() + "\";\n"));
        sb.append(indent(1, "public static final int VERSION = " + iface.version() + ";\n\n"));

        for (EnumDef e : iface.enums()) {
            sb.append(e.bitfield() ? renderBitfield(e) : renderEnum(e));
            sb.append('\n');
        }

        sb.append(renderRequestSealed(iface));
        sb.append('\n');
        sb.append(renderEventSealed(iface));

        sb.append("}\n");
        return sb.toString();
    }

    // ---- javadoc ----------------------------------------------------------

    String renderJavadoc(Description description, int since, OptionalInt deprecatedSince) {
        return renderJavadoc(description, since, deprecatedSince, List.of());
    }

    String renderJavadoc(Description description, int since, OptionalInt deprecatedSince, List<String> extraTags) {
        StringBuilder sb = new StringBuilder();
        sb.append("/**\n");
        if (!description.summary().isEmpty()) {
            sb.append(" * ").append(escapeJavadoc(description.summary())).append("\n");
        }
        if (!description.body().isEmpty()) {
            if (!description.summary().isEmpty()) sb.append(" * <p>\n");
            for (String line : description.body().split("\n")) {
                sb.append(" * ").append(escapeJavadoc(line.stripTrailing())).append("\n");
            }
        }
        for (String tag : extraTags) {
            sb.append(" * ").append(tag).append("\n");
        }
        if (since > 0) {
            sb.append(" * @since ").append(since).append("\n");
        }
        deprecatedSince.ifPresent(d -> sb.append(" * @deprecated since ").append(d).append("\n"));
        sb.append(" */\n");
        return sb.toString();
    }

    private static String escapeJavadoc(String s) {
        // Avoid accidentally closing the comment. Wayland descriptions don't
        // contain HTML markup we need to preserve.
        return s.replace("*/", "*&#47;");
    }

    // ---- enums ------------------------------------------------------------

    String renderEnum(EnumDef e) {
        String name = Names.pascal(e.name());
        String entries = e.entries().stream()
                .map(en -> indent(2, entryJavadocAndDecl(en, false)))
                .collect(Collectors.joining(",\n", "", ";\n"));
        return indent(1, renderJavadoc(e.description(), e.since(), OptionalInt.empty()))
                + indent(1, "public enum %s {\n".formatted(name))
                + entries + "\n"
                + indent(2, "private final int value;\n")
                + indent(2, "%s(int value) { this.value = value; }\n".formatted(name))
                + indent(2, "public int value() { return value; }\n")
                + indent(2, "public static %s fromValue(int v) {\n".formatted(name))
                + indent(3, "for (%s c : values()) if (c.value == v) return c;\n".formatted(name))
                + indent(3, "throw new IllegalArgumentException(\"Unknown %s value: \" + v);\n".formatted(name))
                + indent(2, "}\n")
                + indent(1, "}\n");
    }

    String renderBitfield(EnumDef e) {
        String name = Names.pascal(e.name());
        StringBuilder sb = new StringBuilder();
        sb.append(indent(1, renderJavadoc(e.description(), e.since(), OptionalInt.empty())));
        sb.append(indent(1, "public static final class %s {\n".formatted(name)));
        sb.append(indent(2, "private %s() {}\n".formatted(name)));
        for (EnumEntry en : e.entries()) {
            sb.append(indent(2, entryJavadocAndDecl(en, true)));
            sb.append('\n');
        }
        sb.append(indent(2, "public static int combine(int... flags) {\n"));
        sb.append(indent(3, "int r = 0; for (int f : flags) r |= f; return r;\n"));
        sb.append(indent(2, "}\n"));
        sb.append(indent(2, "public static boolean isSet(int mask, int flag) { return (mask & flag) == flag; }\n"));
        sb.append(indent(1, "}\n"));
        return sb.toString();
    }

    private String entryJavadocAndDecl(EnumEntry en, boolean asConstant) {
        Description desc = en.description().isEmpty() && !en.summary().isEmpty()
                ? new Description(en.summary(), "")
                : en.description();
        String javadoc = renderJavadoc(desc, en.since(), en.deprecatedSince());
        String constName = Names.enumConstant(en.name());
        String deprecation = en.deprecatedSince().isPresent()
                ? "@Deprecated(since = \"" + en.deprecatedSince().getAsInt() + "\") "
                : "";
        if (asConstant) {
            return javadoc + "%spublic static final int %s = %s;".formatted(
                    deprecation, constName, formatEnumLiteral(en.value()));
        }
        return javadoc + "%s%s(%s)".formatted(deprecation, constName, formatEnumLiteral(en.value()));
    }

    private static String formatEnumLiteral(long value) {
        // Bitfield masks are usually presented in hex; small enums in decimal. Keep both compact.
        if (value > 0xff && Long.bitCount(value) == 1) {
            return "0x" + Long.toHexString(value);
        }
        return Long.toString(value);
    }

    // ---- requests / events sealed hierarchies ----------------------------

    String renderRequestSealed(Interface iface) {
        return renderSealed(iface, "Request", iface.requests().stream()
                .map(r -> new MessageView(r.name(), r.opcode(), r.since(), r.deprecatedSince(),
                        r.description(), r.args(), r.destructor()))
                .toList());
    }

    String renderEventSealed(Interface iface) {
        return renderSealed(iface, "Event", iface.events().stream()
                .map(e -> new MessageView(e.name(), e.opcode(), e.since(), e.deprecatedSince(),
                        e.description(), e.args(), false))
                .toList());
    }

    private String renderSealed(Interface iface, String kind, List<MessageView> messages) {
        StringBuilder sb = new StringBuilder();
        if (messages.isEmpty()) {
            sb.append(indent(1, "/** No %s messages defined for this interface. */\n".formatted(kind.toLowerCase())));
            sb.append(indent(1, "public interface %s extends org.wayland4j.protocol.runtime.Message {\n".formatted(kind)));
            sb.append(indent(2, "static %s readPayload(java.io.InputStream in, int opcode, org.wayland4j.protocol.runtime.FdSource fds) throws java.io.IOException {\n".formatted(kind)));
            sb.append(indent(3, "throw new org.wayland4j.protocol.runtime.WireFormatException(\"%s has no %s messages (opcode \" + opcode + \")\");\n"
                    .formatted(iface.name(), kind.toLowerCase())));
            sb.append(indent(2, "}\n"));
            sb.append(indent(1, "}\n"));
            return sb.toString();
        }

        String permits = messages.stream()
                .map(m -> kind + "." + Names.pascal(m.name()))
                .collect(Collectors.joining(", "));

        sb.append(indent(1, "public sealed interface %s extends org.wayland4j.protocol.runtime.Message permits %s {\n".formatted(kind, permits)));
        sb.append(indent(2, "int opcode();\n"));
        sb.append(indent(2, "void writeTo(java.io.OutputStream out, org.wayland4j.protocol.runtime.FdSink fds) throws java.io.IOException;\n\n"));

        for (MessageView m : messages) {
            sb.append(renderMessageRecord(m, kind));
            sb.append('\n');
        }

        sb.append(indent(2, "static %s readPayload(java.io.InputStream in, int opcode, org.wayland4j.protocol.runtime.FdSource fds) throws java.io.IOException {\n".formatted(kind)));
        sb.append(indent(3, "return switch (opcode) {\n"));
        for (MessageView m : messages) {
            String n = Names.pascal(m.name());
            sb.append(indent(4, "case %s.OPCODE -> %s.readFrom(in, fds);\n".formatted(n, n)));
        }
        sb.append(indent(4, "default -> throw new org.wayland4j.protocol.runtime.WireFormatException(\"Unknown %s.%s opcode \" + opcode);\n"
                .formatted(iface.name(), kind.toLowerCase())));
        sb.append(indent(3, "};\n"));
        sb.append(indent(2, "}\n"));

        sb.append(indent(1, "}\n"));
        return sb.toString();
    }

    // ---- one message record ----------------------------------------------

    private String renderMessageRecord(MessageView m, String kind) {
        List<JavaField> fields = expandFields(m.args());
        String name = Names.pascal(m.name());

        List<String> paramTags = new ArrayList<>();
        for (Arg a : m.args()) {
            String desc = a.summary() == null || a.summary().isEmpty() ? "" : a.summary();
            String enumNote = a.enumRef().map(er -> " (enum: "
                            + er.interfaceName().map(in -> Names.pascal(in) + ".").orElse("")
                            + Names.pascal(er.enumName()) + ")")
                    .orElse("");
            String label = Names.camel(a.name());
            paramTags.add("@param %s %s%s".formatted(label, desc, enumNote));
        }

        StringBuilder sb = new StringBuilder();
        sb.append(indent(2, renderJavadoc(m.description(), m.since(), m.deprecatedSince(), paramTags)));

        String params = fields.stream()
                .map(f -> f.javaType() + " " + f.javaName())
                .collect(Collectors.joining(", "));
        if (m.deprecatedSince().isPresent()) {
            sb.append(indent(2, "@Deprecated(since = \"" + m.deprecatedSince().getAsInt() + "\")\n"));
        }
        sb.append(indent(2, "public record %s(%s) implements %s {\n".formatted(name, params, kind)));
        sb.append(indent(3, "public static final int OPCODE = " + m.opcode() + ";\n"));
        sb.append(indent(3, "public static final int SINCE = " + m.since() + ";\n"));
        if (m.destructor()) {
            sb.append(indent(3, "public static final boolean DESTRUCTOR = true;\n"));
        }
        sb.append(indent(3, "@Override public int opcode() { return OPCODE; }\n\n"));

        sb.append(indent(3, "@Override\n"));
        sb.append(indent(3, "public void writeTo(java.io.OutputStream out, org.wayland4j.protocol.runtime.FdSink fds) throws java.io.IOException {\n"));
        for (JavaField f : fields) {
            sb.append(indent(4, f.writerCall() + "\n"));
        }
        sb.append(indent(3, "}\n\n"));

        sb.append(indent(3, "public static %s readFrom(java.io.InputStream in, org.wayland4j.protocol.runtime.FdSource fds) throws java.io.IOException {\n".formatted(name)));
        for (JavaField f : fields) {
            sb.append(indent(4, f.readerDecl() + "\n"));
        }
        String args = fields.stream().map(JavaField::javaName).collect(Collectors.joining(", "));
        sb.append(indent(4, "return new %s(%s);\n".formatted(name, args)));
        sb.append(indent(3, "}\n"));

        sb.append(indent(2, "}\n"));
        return sb.toString();
    }

    // ---- arg → java field mapping ----------------------------------------

    private List<JavaField> expandFields(List<Arg> args) {
        List<JavaField> out = new ArrayList<>();
        for (Arg a : args) {
            String fieldName = Names.camel(a.name());
            if (a.inlineNewIdInterface()) {
                // Expand new_id-with-no-interface into three wire fields.
                out.add(new JavaField(
                        "interfaceName", "java.lang.String",
                        "org.wayland4j.protocol.runtime.WireIO.writeString(out, interfaceName);",
                        "java.lang.String interfaceName = org.wayland4j.protocol.runtime.WireIO.readString(in);"));
                out.add(new JavaField(
                        "version", "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeUInt(out, version);",
                        "int version = org.wayland4j.protocol.runtime.WireIO.readUInt(in);"));
                out.add(new JavaField(
                        fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeNewId(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readNewId(in);"));
                continue;
            }
            out.add(switch (a.type()) {
                case INT -> new JavaField(fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeInt(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readInt(in);");
                case UINT -> new JavaField(fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeUInt(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readUInt(in);");
                case FIXED -> new JavaField(fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeFixedRaw(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readFixedRaw(in);");
                case STRING -> new JavaField(fieldName, "java.lang.String",
                        "org.wayland4j.protocol.runtime.WireIO.writeString" + nullableSuffix(a) + "(out, " + fieldName + ");",
                        "java.lang.String " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readString" + nullableSuffix(a) + "(in);");
                case OBJECT -> new JavaField(fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeObject" + nullableSuffix(a) + "(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readObject" + nullableSuffix(a) + "(in);");
                case NEW_ID -> new JavaField(fieldName, "int",
                        "org.wayland4j.protocol.runtime.WireIO.writeNewId(out, " + fieldName + ");",
                        "int " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readNewId(in);");
                case ARRAY -> new JavaField(fieldName, "byte[]",
                        "org.wayland4j.protocol.runtime.WireIO.writeArray(out, " + fieldName + ");",
                        "byte[] " + fieldName + " = org.wayland4j.protocol.runtime.WireIO.readArray(in);");
                case FD -> new JavaField(fieldName, "int",
                        "fds.push(" + fieldName + ");",
                        "int " + fieldName + " = fds.pop();");
            });
        }
        return out;
    }

    private static String nullableSuffix(Arg a) {
        return a.allowNull() ? "Nullable" : "";
    }

    // ---- helpers ----------------------------------------------------------

    private static String indent(int level, String s) {
        String pad = "    ".repeat(level);
        if (s.isEmpty()) return s;
        StringBuilder sb = new StringBuilder(s.length() + pad.length() * 4);
        boolean atLineStart = true;
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (atLineStart && c != '\n') sb.append(pad);
            sb.append(c);
            atLineStart = c == '\n';
        }
        return sb.toString();
    }

    private record JavaField(String javaName, String javaType, String writerCall, String readerDecl) {}

    private record MessageView(
            String name,
            int opcode,
            int since,
            OptionalInt deprecatedSince,
            Description description,
            List<Arg> args,
            boolean destructor) {}
}
