package org.wayland4j.protocol.apt;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.wayland4j.protocol.model.Arg;
import org.wayland4j.protocol.model.ArgType;
import org.wayland4j.protocol.model.EnumDef;
import org.wayland4j.protocol.model.EnumEntry;
import org.wayland4j.protocol.model.Event;
import org.wayland4j.protocol.model.Interface;
import org.wayland4j.protocol.model.Request;
import org.wayland4j.protocol.scanner.JavaIdentifiers;
import org.wayland4j.protocol.scanner.SignatureEncoder;

/**
 * Emits one Java source file per Wayland {@code <interface>}.
 */
final class InterfaceClassEmitter {

    private final String pkg;
    private final Interface iface;
    private final JavaTypeMapper types;
    private final String typeName;

    InterfaceClassEmitter(String pkg, Interface iface, Map<String, String> interfaceToPackage) {
        this.pkg = pkg;
        this.iface = iface;
        this.types = new JavaTypeMapper(pkg, interfaceToPackage);
        this.typeName = JavaIdentifiers.typeName(iface.name());
    }

    String emit() {
        StringBuilder sb = new StringBuilder(8192);
        sb.append("// Generated by wayland4j: do not edit.\n");
        sb.append("package ").append(pkg).append(";\n\n");
        sb.append("import java.lang.foreign.MemorySegment;\n");
        sb.append("import org.wayland4j.client.Proxy;\n");
        sb.append("import org.wayland4j.client.internal.DispatchTable;\n");
        sb.append("import org.wayland4j.client.internal.ProxyRegistry;\n\n");

        emitDoc(sb, "", iface.description());
        boolean autoCloseable = iface.hasDestructor();
        sb.append("public class ").append(typeName).append(" extends Proxy");
        if (autoCloseable) sb.append(" implements AutoCloseable");
        sb.append(" {\n\n");

        sb.append("    public static final String INTERFACE_NAME = \"").append(iface.name()).append("\";\n");
        sb.append("    public static final int INTERFACE_VERSION = ").append(iface.version()).append(";\n\n");

        emitEnums(sb);
        emitListener(sb);
        emitDispatchTable(sb);

        sb.append("    public ").append(typeName).append("(MemorySegment ptr) { super(ptr); }\n\n");

        if (!iface.events().isEmpty()) {
            sb.append("    public void setListener(Listener listener) {\n");
            sb.append("        ProxyRegistry.setListener(this, listener);\n");
            sb.append("    }\n\n");
        }

        for (Request r : iface.requests()) {
            emitRequest(sb, r);
        }

        sb.append("}\n");
        return sb.toString();
    }

    private void emitEnums(StringBuilder sb) {
        for (EnumDef e : iface.enums()) {
            String name = JavaIdentifiers.upperCamel(e.name());
            emitDoc(sb, "    ", e.description());
            sb.append("    public static final class ").append(name).append(" {\n");
            sb.append("        private ").append(name).append("() {}\n");
            for (EnumEntry entry : e.entries()) {
                emitDoc(sb, "        ", entry.summary());
                sb.append("        public static final int ")
                        .append(JavaIdentifiers.constantName(entry.name()))
                        .append(" = ")
                        .append(formatIntLiteral(entry.value()))
                        .append(";\n");
            }
            sb.append("    }\n\n");
        }
    }

    private void emitListener(StringBuilder sb) {
        if (iface.events().isEmpty()) return;
        sb.append("    public interface Listener {\n");
        for (Event ev : iface.events()) {
            emitEventDoc(sb, ev);
            sb.append("        void ").append(JavaIdentifiers.methodName(ev.name())).append("(");
            sb.append(typeName).append(" self");
            for (Arg a : ev.args()) {
                sb.append(", ").append(types.eventParamType(a)).append(' ')
                        .append(JavaIdentifiers.fieldName(a.name()));
            }
            sb.append(");\n");
        }
        sb.append("    }\n\n");
    }

    private void emitDispatchTable(StringBuilder sb) {
        sb.append("    public static final DispatchTable DISPATCH_TABLE = new DispatchTable(new DispatchTable.EventDispatcher[] {\n");
        for (Event ev : iface.events()) {
            sb.append("        (proxy, listener, args) -> ((Listener) listener).")
                    .append(JavaIdentifiers.methodName(ev.name())).append("((")
                    .append(typeName).append(") proxy");
            int slot = 0;
            for (Arg a : ev.args()) {
                sb.append(", ");
                sb.append(eventArgExtract(a, slot));
                slot++;
            }
            sb.append("),\n");
        }
        sb.append("    }, new boolean[] {");
        boolean first = true;
        for (Event ev : iface.events()) {
            if (!first) sb.append(", ");
            sb.append(ev.destructor());
            first = false;
        }
        sb.append("});\n\n");
    }

    private String eventArgExtract(Arg a, int slot) {
        return switch (a.type()) {
            case INT, UINT, FD -> "((Integer) args[" + slot + "]).intValue()";
            case FIXED -> "org.wayland4j.client.internal.WlArgumentLayout.fixedToDouble((Integer) args[" + slot + "])";
            case STRING -> "(String) args[" + slot + "]";
            case ARRAY -> "(byte[]) args[" + slot + "]";
            case OBJECT, NEW_ID -> "(" + types.eventParamType(a) + ") args[" + slot + "]";
        };
    }

    private void emitRequest(StringBuilder sb, Request r) {
        // Special-case wl_registry.bind: dynamic new_id without fixed interface.
        if (r.isDynamicConstructor()) {
            emitBindRequest(sb, r);
            return;
        }

        Arg newIdArg = r.newIdArg();
        boolean isConstructor = newIdArg != null;
        String returnType = "void";
        if (isConstructor) {
            returnType = newIdArg.interfaceName() == null
                    ? "org.wayland4j.client.Proxy"
                    : types.qualified(newIdArg.interfaceName());
        }

        // Build parameter list (skipping the new_id arg).
        List<String> params = new ArrayList<>();
        List<String> marshalArgs = new ArrayList<>();
        List<Arg> docArgs = new ArrayList<>();
        for (Arg a : r.args()) {
            if (a.type() == ArgType.NEW_ID) continue;
            String p = types.requestParamType(a) + " " + JavaIdentifiers.fieldName(a.name());
            params.add(p);
            marshalArgs.add(JavaIdentifiers.fieldName(a.name()));
            docArgs.add(a);
        }

        String signature = SignatureEncoder.forRequest(r.since(), r.args());

        emitRequestDoc(sb, r, docArgs);
        String methodName = JavaIdentifiers.methodName(r.name());
        sb.append("    public ").append(returnType).append(' ').append(methodName).append('(');
        sb.append(String.join(", ", params));
        sb.append(") {\n");

        if (r.destructor()) {
            sb.append("        Proxy.sendDestroy(this, ").append(r.opcode()).append(", \"")
                    .append(escape(signature)).append("\"");
            for (String a : marshalArgs) sb.append(", ").append(a);
            sb.append(");\n");
        } else if (isConstructor) {
            String returnClass = newIdArg.interfaceName() == null
                    ? "org.wayland4j.client.Proxy"
                    : types.qualified(newIdArg.interfaceName());
            sb.append("        return Proxy.sendConstructor(this, ").append(r.opcode())
                    .append(", 0, ").append(returnClass).append(".class, \"")
                    .append(escape(signature)).append("\"");
            for (String a : marshalArgs) sb.append(", ").append(a);
            sb.append(");\n");
        } else {
            sb.append("        Proxy.sendVoid(this, ").append(r.opcode()).append(", 0, \"")
                    .append(escape(signature)).append("\"");
            for (String a : marshalArgs) sb.append(", ").append(a);
            sb.append(");\n");
        }
        sb.append("    }\n\n");

        // For destructor requests, also emit close() to satisfy AutoCloseable.
        if (r.destructor()) {
            sb.append("    @Override public void close() { ").append(methodName).append("(); }\n\n");
        }
    }

    private void emitBindRequest(StringBuilder sb, Request r) {
        emitRequestDoc(sb, r, List.of());
        String methodName = JavaIdentifiers.methodName(r.name());
        sb.append("    public <P extends Proxy> P ").append(methodName)
                .append("(int name, Class<P> proxyClass, int version) {\n");
        sb.append("        return Proxy.sendBind(this, ").append(r.opcode())
                .append(", name, proxyClass, version);\n");
        sb.append("    }\n\n");
    }

    private void emitRequestDoc(StringBuilder sb, Request r, List<Arg> args) {
        if (!hasDoc(r.description()) && argsHaveSummaries(args)) {
            sb.append("    /**\n");
            for (Arg a : args) {
                if (a.summary() != null && !a.summary().isBlank()) {
                    sb.append("     * @param ").append(JavaIdentifiers.fieldName(a.name())).append(' ')
                            .append(escapeJavadoc(a.summary())).append('\n');
                }
            }
            sb.append("     */\n");
            return;
        }
        if (!hasDoc(r.description()) && args.isEmpty()) return;
        sb.append("    /**\n");
        if (hasDoc(r.description())) {
            for (String line : wrapJavadoc(r.description())) {
                sb.append("     * ").append(line).append('\n');
            }
        }
        if (argsHaveSummaries(args)) {
            sb.append("     *\n");
            for (Arg a : args) {
                if (a.summary() != null && !a.summary().isBlank()) {
                    sb.append("     * @param ").append(JavaIdentifiers.fieldName(a.name())).append(' ')
                            .append(escapeJavadoc(a.summary())).append('\n');
                }
            }
        }
        sb.append("     */\n");
    }

    private void emitEventDoc(StringBuilder sb, Event ev) {
        boolean argSummaries = argsHaveSummaries(ev.args());
        if (!hasDoc(ev.description()) && !argSummaries) return;
        sb.append("        /**\n");
        if (hasDoc(ev.description())) {
            for (String line : wrapJavadoc(ev.description())) {
                sb.append("         * ").append(line).append('\n');
            }
        }
        if (argSummaries) {
            if (hasDoc(ev.description())) sb.append("         *\n");
            for (Arg a : ev.args()) {
                if (a.summary() != null && !a.summary().isBlank()) {
                    sb.append("         * @param ").append(JavaIdentifiers.fieldName(a.name())).append(' ')
                            .append(escapeJavadoc(a.summary())).append('\n');
                }
            }
        }
        sb.append("         */\n");
    }

    private static boolean hasDoc(String s) {
        return s != null && !s.isBlank();
    }

    private static boolean argsHaveSummaries(List<Arg> args) {
        for (Arg a : args) {
            if (a.summary() != null && !a.summary().isBlank()) return true;
        }
        return false;
    }

    private static void emitDoc(StringBuilder sb, String indent, String description) {
        if (!hasDoc(description)) return;
        sb.append(indent).append("/**\n");
        for (String line : wrapJavadoc(description)) {
            sb.append(indent).append(" * ").append(line).append('\n');
        }
        sb.append(indent).append(" */\n");
    }

    private static String escapeJavadoc(String s) {
        return s.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("@", "&#64;")
                .replace("*/", "*&#47;");
    }

    private static List<String> wrapJavadoc(String description) {
        List<String> out = new ArrayList<>();
        for (String paragraph : description.split("\\R\\R+")) {
            String text = paragraph.replaceAll("\\s+", " ").strip();
            if (text.isEmpty()) continue;
            if (!out.isEmpty()) out.add("");
            wrapLine(escapeJavadoc(text), 96, out);
        }
        return out;
    }

    private static void wrapLine(String text, int width, List<String> out) {
        StringBuilder cur = new StringBuilder();
        for (String word : text.split(" ")) {
            if (cur.length() == 0) {
                cur.append(word);
                continue;
            }
            if (cur.length() + 1 + word.length() > width) {
                out.add(cur.toString());
                cur.setLength(0);
                cur.append(word);
            } else {
                cur.append(' ').append(word);
            }
        }
        if (cur.length() > 0) out.add(cur.toString());
    }

    private static String formatIntLiteral(long value) {
        // Most Wayland enum values are small positive ints. Hex for big values to avoid overflow oddities.
        if (value < 0 || value > Integer.MAX_VALUE) {
            return "0x" + Long.toHexString(value & 0xFFFFFFFFL).toUpperCase();
        }
        return Long.toString(value);
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
