package org.wayland4j.protocol.apt;

import java.util.ArrayList;
import java.util.List;
import org.wayland4j.protocol.model.Arg;
import org.wayland4j.protocol.model.ArgType;
import org.wayland4j.protocol.model.Event;
import org.wayland4j.protocol.model.Interface;
import org.wayland4j.protocol.model.Protocol;
import org.wayland4j.protocol.model.Request;
import org.wayland4j.protocol.scanner.JavaIdentifiers;
import org.wayland4j.protocol.scanner.SignatureEncoder;

/**
 * Emits a single {@code WaylandProtocols} class that bootstraps the
 * {@code wl_interface} graph and registers every generated proxy class with
 * the runtime registry.
 */
final class ProtocolsClassEmitter {

    private final String pkg;
    private final Protocol protocol;

    ProtocolsClassEmitter(String pkg, Protocol protocol) {
        this.pkg = pkg;
        this.protocol = protocol;
    }

    String emit() {
        StringBuilder sb = new StringBuilder(16384);
        sb.append("// Generated by wayland4j: do not edit.\n");
        sb.append("package ").append(pkg).append(";\n\n");
        sb.append("import java.lang.foreign.MemorySegment;\n");
        sb.append("import java.util.Map;\n");
        sb.append("import org.wayland4j.client.internal.Wayland;\n");
        sb.append("import org.wayland4j.client.internal.WlInterfaceArena;\n");
        sb.append("import org.wayland4j.client.internal.WlInterfaceArena.Descriptor;\n");
        sb.append("import org.wayland4j.client.internal.WlInterfaceArena.Message;\n\n");

        sb.append("public final class WaylandProtocols {\n\n");
        sb.append("    private WaylandProtocols() {}\n\n");

        // MemorySegment field per interface for callers that want it.
        for (Interface i : protocol.interfaces()) {
            sb.append("    public static final MemorySegment ").append(constName(i.name())).append(";\n");
        }
        sb.append('\n');

        sb.append("    static {\n");
        sb.append("        Descriptor[] descriptors = new Descriptor[] {\n");
        for (Interface i : protocol.interfaces()) {
            emitDescriptor(sb, i);
        }
        sb.append("        };\n");
        sb.append("        Map<String, MemorySegment> built = WlInterfaceArena.populate(descriptors);\n");
        for (Interface i : protocol.interfaces()) {
            sb.append("        ").append(constName(i.name())).append(" = built.get(\"")
                    .append(i.name()).append("\");\n");
        }
        sb.append('\n');
        for (Interface i : protocol.interfaces()) {
            String typeName = JavaIdentifiers.typeName(i.name());
            sb.append("        Wayland.register(")
                    .append(typeName).append(".class, \"")
                    .append(i.name()).append("\", ")
                    .append(i.version()).append(", ")
                    .append(constName(i.name())).append(", ")
                    .append(typeName).append(".DISPATCH_TABLE, ")
                    .append(typeName).append("::new);\n");
        }
        sb.append("    }\n");
        sb.append("}\n");
        return sb.toString();
    }

    private void emitDescriptor(StringBuilder sb, Interface i) {
        sb.append("            new Descriptor(\"").append(i.name()).append("\", ")
                .append(i.version()).append(",\n");
        sb.append("                new Message[] {\n");
        for (Request r : i.requests()) {
            String sig = SignatureEncoder.forRequest(r.since(), r.args());
            String[] typesArr = requestTypes(r);
            emitMessage(sb, r.name(), sig, typesArr);
        }
        sb.append("                },\n");
        sb.append("                new Message[] {\n");
        for (Event e : i.events()) {
            String sig = SignatureEncoder.forEvent(e.since(), e.args());
            String[] typesArr = eventTypes(e);
            emitMessage(sb, e.name(), sig, typesArr);
        }
        sb.append("                }),\n");
    }

    private void emitMessage(StringBuilder sb, String name, String signature, String[] types) {
        sb.append("                    new Message(\"").append(name).append("\", \"")
                .append(escape(signature)).append("\", new String[] {");
        for (int i = 0; i < types.length; i++) {
            if (i > 0) sb.append(", ");
            sb.append(types[i] == null ? "null" : "\"" + types[i] + "\"");
        }
        sb.append("}),\n");
    }

    private static String[] requestTypes(Request r) {
        List<String> out = new ArrayList<>();
        for (Arg a : r.args()) {
            if (a.type() == ArgType.NEW_ID && a.interfaceName() == null) {
                out.add(null); // s
                out.add(null); // u
                out.add(null); // n
            } else if (a.type() == ArgType.OBJECT || a.type() == ArgType.NEW_ID) {
                out.add(a.interfaceName());
            } else {
                out.add(null);
            }
        }
        return out.toArray(String[]::new);
    }

    private static String[] eventTypes(Event e) {
        List<String> out = new ArrayList<>();
        for (Arg a : e.args()) {
            if (a.type() == ArgType.OBJECT || a.type() == ArgType.NEW_ID) {
                out.add(a.interfaceName());
            } else {
                out.add(null);
            }
        }
        return out.toArray(String[]::new);
    }

    private static String constName(String wlInterfaceName) {
        return wlInterfaceName.toUpperCase();
    }

    private static String escape(String s) {
        return s.replace("\\", "\\\\").replace("\"", "\\\"");
    }
}
